# Generated by Django 5.1 on 2024-08-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopowner',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='shopowner',
            name='license_certificate',
            field=models.FileField(null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='ownername',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='shopname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
