# Generated by Django 5.1 on 2024-08-15 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_rename_name_shopowner_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopowner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shopowner',
            name='password',
        ),
        migrations.RemoveField(
            model_name='shopowner',
            name='username',
        ),
        migrations.AddField(
            model_name='shopowner',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shopowner_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
