# Generated by Django 5.1 on 2024-08-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_shopowner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopowner',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
