# Generated by Django 5.1 on 2024-08-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_shopowner_is_approved_shopowner_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopowner',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='shopowner',
            name='rejection_reason',
        ),
    ]
