# Generated by Django 5.1 on 2024-08-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_remove_shopowner_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopowner',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
