# Generated by Django 5.1 on 2024-08-22 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_shopowner_reject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopowner',
            old_name='reject',
            new_name='rejected',
        ),
    ]
