# Generated by Django 5.1 on 2024-09-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_rename_reject_shopowner_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_company', models.CharField(max_length=200, null=True)),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('product_type', models.CharField()),
                ('fuel_type', models.CharField()),
                ('model_no', models.IntegerField()),
                ('photo', models.FileField(null=True, upload_to='photos/')),
            ],
        ),
    ]
