# Generated by Django 5.1 on 2024-09-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0013_rename_fuel_type_product_gear_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gear_transmission',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('EV', 'EV'), ('diesel', 'Diesel'), ('petrol', 'Petrol')], max_length=50, null=True),
        ),
    ]
