# Generated by Django 5.1 on 2024-09-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0016_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
