# Generated by Django 5.1 on 2024-09-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0020_alter_product_shop_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop_owner',
        ),
    ]
