# Generated by Django 5.1 on 2024-08-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
